#!/usr/bin/env bash
set -euo pipefail

# Machine-enforced architecture constraint checker.
# Verifies that import/dependency boundaries defined in architecture.md are respected.
# Generated by default during setup. Runs automatically during critic-runtime and maintain.
#
# Exit code: 0 = PASS, 1 = FAIL (violations found)

echo "=== Architecture Check ==="

FAIL=0

# Example: Check that domain layer does not import from infra
# Uncomment and adapt to your project:
#
# if grep -r "from.*infra" src/domain/ 2>/dev/null; then
#   echo "  FAIL: domain/ imports from infra/ — violates layer boundary"
#   ((FAIL++))
# else
#   echo "  PASS: domain/ does not import from infra/"
# fi
#
# if grep -r "from.*api" src/domain/ 2>/dev/null; then
#   echo "  FAIL: domain/ imports from api/ — violates layer boundary"
#   ((FAIL++))
# else
#   echo "  PASS: domain/ does not import from api/"
# fi

echo "  (no project-specific constraints configured yet — edit architecture.md and this script)"

if [[ "$FAIL" -gt 0 ]]; then
  echo "VERDICT: FAIL ($FAIL violations)"
  exit 1
else
  echo "VERDICT: PASS"
  exit 0
fi
